version: '3'

services:
  forward-proxy:
    image: marimo1110/nginx_forward_proxy
    volumes:
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
    restart: unless-stopped
    ports:
      - 3128:3128
